version: '3.0'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3309:3306'
    volumes:
      - './mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes


  wordpress:
    image: 'bitnami/wordpress:latest'
    ports:
      - 13080:80
      - 13443:443
    volumes:
      - './wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes

