kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ethicaltree-blog-wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: do-block-storage
